security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
    access_control:
         - { path: /articles, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: /article/create, roles: ROLE_USER }
         - { path: /register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
